### ISSUE TITLE
Incorrect transpiling of Flow array spread operator in arguments

### ISSUE THREAD

**Issue by biniek-io** [khell/flow-to-ts#5] opened 2019-08-30 03:41 UTC
Flow:
`
export const promiseAllWithTiming = <T: $ReadOnlyArray<mixed>>(
    promiseFactoryFn: (...T) => Promise<any>[],
    callback: (number[]) => void,
): ((...T) => Promise<any>) => async (...args: T): Promise<any> => {
`

Transiled TS error:
`
 > 109 | export const promiseAllWithTiming = <T extends ReadonlyArray<unknown>>(promiseFactoryFn: (...: T) => Promise<any>[], callback: (arg0: number[]) => undefined): (...: T) => Promise<any> => async (...args: T): Promise<any> => {
`

Expected behaviour:
`...T` should stay

**Comment by khell** [comment] 2019-09-18 09:33
Both the Babel parser `@babel/parser@7.6.0` and the current Flow parser `flow-parser` parse this form of untyped rest spread in function params as a type annotation, which is why the transpiled result seemingly "moves" `T` over to the type annotation right side. I thought this was initially a bug in Babel, but with the official `flow-parser` doing the same thing, I suspect this may possibly not be valid Flow syntax. The problem is fixed if you annotate all rest spread in function params with a type.

More investigation required.

**Comment by khell** [comment] 2019-09-19 05:01
We're throwing an error for now in #10. The parsing issue should be fixed in @babel/parser.

**Closed as completed by khell** 2019-09-19 05:01 UTC
